keys = %w{
  CI_BRANCH
  CI_BUILD_ID
  CI_COMMITTER_EMAIL
  CI_COMMITTER_NAME
  CI_COMMITTER_USERNAME
  CI_COMMIT_DESCRIPTION
  CI_COMMIT_ID
  CI_COMMIT_MESSAGE
  CI_NAME
  CI_PROJECT_ID
  CI_REPO_NAME
  CI_STRING_TIME
  CI_TIMESTAMP
  DECLARED_ENV_FROM_YML
  DECLARED_ENV_FROM_DOCKERFILE
  PASSING_THROUGH_BUILD_ARG_ENV
  NEW_VAR
}

result = keys.each do |k|
  val = ENV[k]
  puts "#{k}: #{val}"
end
